# Generated by Django 2.2.4 on 2019-08-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190808_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='price',
            new_name='price_rate',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Genre'),
        ),
    ]
